-- GENERATED by scripts/generate-seed.ts from seed-madrid.json. Do not edit.
--
-- Demo profiles, venues and plans exist so the deck is never empty in
-- development. Every row carries is_seed = true:
--
--   delete from plans where is_seed; delete from profiles where is_seed;
--
-- 01-PRD §Cold start: a deck that is mostly seed data with nobody joining is
-- worse than a small honest deck. Delete these as real supply arrives.

-- Whole weeks to add to every seeded plan so the deck always sits in the
-- future. Written inline rather than as a temporary table so the file applies
-- identically through psql, the Supabase CLI and the management API, none of
-- which agree about session state.
create or replace function seed_shift_days() returns int
language sql stable as $fn$
  select greatest(
           0,
           ceil(extract(epoch from (now() + interval '12 hours' - timestamptz '2026-09-04T17:00:00.000Z'))
                / 604800.0)
         )::int * 7;
$fn$;


-- ── venues ──────────────────────────────────────────────────────────────────
insert into venues (id, slug, name, kind, distrito, lat, lng, verified, is_seed) values
  ('16beb95a-c1fd-5efc-8c1c-ebe1e84cda37', 'v_retiro_alcala', 'Parque del Retiro — Puerta de Alcalá', 'parque', 'Retiro', 40.42, -3.6883, false, true),
  ('a0b22164-e500-5167-8d98-912bf89ea34e', 'v_retiro_estanque', 'Parque del Retiro — Estanque Grande', 'parque', 'Retiro', 40.418, -3.683, false, true),
  ('5a346390-1187-560d-81ba-77df35af0353', 'v_debod', 'Templo de Debod', 'parque', 'Moncloa-Aravaca', 40.424, -3.7175, false, true),
  ('4fd24052-c971-59c0-8842-e00b7d726616', 'v_madrid_rio', 'Madrid Río — Puente de Toledo', 'parque', 'Arganzuela', 40.396, -3.713, false, true),
  ('36e8a558-5e16-587f-8835-86496143a169', 'v_matadero', 'Matadero Madrid', 'parque', 'Arganzuela', 40.392, -3.698, false, true),
  ('c865aab3-0e14-5a54-8a81-67e4082bc9a9', 'v_casa_campo_lago', 'Casa de Campo — Lago', 'parque', 'Moncloa-Aravaca', 40.418, -3.728, false, true),
  ('27b93037-03c3-5bd0-80c8-b5a2b30c785e', 'v_parque_oeste', 'Parque del Oeste — Rosaleda', 'parque', 'Moncloa-Aravaca', 40.431, -3.723, false, true),
  ('abde3ccc-5bc7-5ebd-842b-394b556d39e4', 'v_dehesa_villa', 'Dehesa de la Villa', 'parque', 'Moncloa-Aravaca', 40.457, -3.722, false, true),
  ('c2f7189f-75c9-5366-88d1-2127006b5545', 'v_berlin', 'Parque de Berlín', 'parque', 'Chamartín', 40.464, -3.679, false, true),
  ('abfc2ad1-57c7-5339-81eb-1b0ec03b4cf0', 'v_juan_carlos', 'Parque Juan Carlos I', 'parque', 'Barajas', 40.462, -3.61, false, true),
  ('ceddc6fc-64dc-5e0d-811d-1b5ddd4e1dff', 'v_cuna_verde', 'Cuña Verde de O''Donnell', 'parque', 'Moratalaz', 40.423, -3.635, false, true),
  ('debbdba2-0431-5e76-8ba2-55e09adb5036', 'v_cdm_vallehermoso', 'CDM Vallehermoso', 'polideportivo', 'Chamberí', 40.442, -3.706, false, true),
  ('6a5f6ab2-e48c-5201-828f-74fbc644dbfb', 'v_padel_chamberi', 'Pistas de pádel — Chamberí (por confirmar)', 'pista', 'Chamberí', 40.438, -3.703, false, true),
  ('28692441-bf02-5052-8ca1-8c9ac1ef71da', 'v_padel_salamanca', 'Pistas de pádel — Salamanca (por confirmar)', 'pista', 'Salamanca', 40.429, -3.679, false, true),
  ('4f5ab9a0-70ca-55d3-84f3-45be1683fcf7', 'v_futbol7_centro', 'Campo de fútbol 7 — Centro (por confirmar)', 'pista', 'Centro', 40.415, -3.705, false, true),
  ('3f41657c-6aa8-5698-829b-67e9eb3dfc78', 'v_rocodromo_1', 'Rocódromo — Chamberí (por confirmar)', 'rocodromo', 'Chamberí', 40.44, -3.698, false, true),
  ('4058b9d3-ae67-5e6a-80d3-41751c90ebe1', 'v_cafe_malasana', 'Café en Malasaña', 'cafe', 'Centro', 40.426, -3.703, false, true),
  ('123bd668-b801-56f6-8b65-356468d28d2a', 'v_cafe_chamberi', 'Café en Chamberí', 'cafe', 'Chamberí', 40.436, -3.702, false, true),
  ('455d1cd0-a375-5719-80c0-2b6c53a89d2f', 'v_bar_lavapies', 'Bar en Lavapiés', 'cafe', 'Centro', 40.409, -3.701, false, true)
on conflict (id) do update set
  name = excluded.name, kind = excluded.kind, distrito = excluded.distrito,
  lat = excluded.lat, lng = excluded.lng, verified = excluded.verified;

-- ── demo accounts ───────────────────────────────────────────────────────────
-- Shadow auth rows with no password: they cannot sign in, they only exist so
-- the profiles foreign key holds.
insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, created_at, updated_at) values
  ('00000000-0000-0000-0000-000000000000', 'e82fe963-b112-52e8-801d-d96a821bbe09', 'authenticated', 'authenticated', 'seed.p1@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', '86eabb55-dac2-5716-8817-45c60e857a92', 'authenticated', 'authenticated', 'seed.p2@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', '3aac0bdc-073a-58b6-86d9-63cf91dad2f5', 'authenticated', 'authenticated', 'seed.p3@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', '91cbe3c1-9c48-5eeb-8007-5c731ae2c526', 'authenticated', 'authenticated', 'seed.p4@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', '0860daa4-3ee9-5a39-821c-4c377931613c', 'authenticated', 'authenticated', 'seed.p5@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', 'ddfcc222-85b7-52c1-8e5f-a97049c85617', 'authenticated', 'authenticated', 'seed.p6@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', 'f81f6254-c330-5816-8654-0078b030e002', 'authenticated', 'authenticated', 'seed.p7@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', '4da925aa-66d6-5e02-8046-46a8cd5e197f', 'authenticated', 'authenticated', 'seed.p8@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', 'd799f45e-241d-5a1f-81b5-a4c06b9f81d1', 'authenticated', 'authenticated', 'seed.p9@dorsal.invalid', now(), now(), now()),
  ('00000000-0000-0000-0000-000000000000', 'b1b0b994-6363-5ecf-81b4-7751f9954aa3', 'authenticated', 'authenticated', 'seed.p10@dorsal.invalid', now(), now(), now())
on conflict (id) do nothing;

insert into profiles (id, dorsal_number, display_name, birth_year, gender, distrito, travel_km, bio, is_seed) values
  ('e82fe963-b112-52e8-801d-d96a821bbe09', 1, 'Marta', 1996, 'mujer'::gender_decl, 'Chamberí', 6, 'Corro por Chamberí. Siempre me quedo al café.', true),
  ('86eabb55-dac2-5716-8817-45c60e857a92', 2, 'Javi', 1993, 'hombre'::gender_decl, 'Salamanca', 8, 'Pádel tres veces por semana. Nivel honesto, prometo.', true),
  ('3aac0bdc-073a-58b6-86d9-63cf91dad2f5', 3, 'Lucía', 1999, 'mujer'::gender_decl, 'Centro', 5, 'Recién llegada a Madrid, buscando gente para entrenar.', true),
  ('91cbe3c1-9c48-5eeb-8007-5c731ae2c526', 4, 'Dani', 1991, 'hombre'::gender_decl, 'Arganzuela', 10, 'Organizo la pachanga del domingo desde hace cuatro años.', true),
  ('0860daa4-3ee9-5a39-821c-4c377931613c', 5, 'Nerea', 1997, 'mujer'::gender_decl, 'Chamberí', 6, 'Boulder y series. No corro rápido pero llego.', true),
  ('ddfcc222-85b7-52c1-8e5f-a97049c85617', 6, 'Álvaro', 1989, 'hombre'::gender_decl, 'Chamartín', 12, 'Salidas largas en carretera los sábados.', true),
  ('f81f6254-c330-5816-8654-0078b030e002', 7, 'Claudia', 1995, 'mujer'::gender_decl, 'Retiro', 5, 'Rodajes suaves y desayuno después. Ese es el plan.', true),
  ('4da925aa-66d6-5e02-8046-46a8cd5e197f', 8, 'Iker', 1994, 'hombre'::gender_decl, 'Centro', 7, 'Pádel, y si hace bueno, bici.', true),
  ('d799f45e-241d-5a1f-81b5-a4c06b9f81d1', 9, 'Sara', 1998, 'mujer'::gender_decl, 'Tetuán', 8, 'Hyrox y todo lo que duela un rato.', true),
  ('b1b0b994-6363-5ecf-81b4-7751f9954aa3', 10, 'Pablo', 1992, 'hombre'::gender_decl, 'Salamanca', 6, 'Baloncesto 3x3 y cañas después, en ese orden.', true)
on conflict (id) do update set
  display_name = excluded.display_name, distrito = excluded.distrito,
  travel_km = excluded.travel_km, bio = excluded.bio;

insert into user_sports (user_id, sport, level_norm) values
  ('e82fe963-b112-52e8-801d-d96a821bbe09', 'running'::sport_key, 5),
  ('e82fe963-b112-52e8-801d-d96a821bbe09', 'escalada'::sport_key, 5),
  ('86eabb55-dac2-5716-8817-45c60e857a92', 'padel'::sport_key, 6),
  ('86eabb55-dac2-5716-8817-45c60e857a92', 'running'::sport_key, 4),
  ('3aac0bdc-073a-58b6-86d9-63cf91dad2f5', 'running'::sport_key, 4),
  ('3aac0bdc-073a-58b6-86d9-63cf91dad2f5', 'yoga'::sport_key, 3),
  ('91cbe3c1-9c48-5eeb-8007-5c731ae2c526', 'futbol'::sport_key, 6),
  ('0860daa4-3ee9-5a39-821c-4c377931613c', 'escalada'::sport_key, 8),
  ('0860daa4-3ee9-5a39-821c-4c377931613c', 'running'::sport_key, 5),
  ('ddfcc222-85b7-52c1-8e5f-a97049c85617', 'ciclismo'::sport_key, 7),
  ('f81f6254-c330-5816-8654-0078b030e002', 'running'::sport_key, 4),
  ('4da925aa-66d6-5e02-8046-46a8cd5e197f', 'padel'::sport_key, 4),
  ('4da925aa-66d6-5e02-8046-46a8cd5e197f', 'ciclismo'::sport_key, 5),
  ('d799f45e-241d-5a1f-81b5-a4c06b9f81d1', 'hyrox'::sport_key, 6),
  ('d799f45e-241d-5a1f-81b5-a4c06b9f81d1', 'running'::sport_key, 7),
  ('b1b0b994-6363-5ecf-81b4-7751f9954aa3', 'baloncesto'::sport_key, 5)
on conflict (user_id, sport) do update set level_norm = excluded.level_norm;

-- ── plans ───────────────────────────────────────────────────────────────────
insert into plans (
  id, host_id, sport, starts_at, duration_min, venue_id, distrito,
  level_min, level_max, level_display, capacity, third_half, third_half_venue_id,
  audience, meeting_note, is_seed
)
select v.id, v.host_id, v.sport, v.starts_at + make_interval(days => seed_shift_days()),
       v.duration_min, v.venue_id, v.distrito, v.level_min, v.level_max, v.level_display,
       v.capacity, v.third_half, v.third_half_venue_id, v.audience, v.meeting_note, true
from (values
  ('d28c2059-c9e6-50c8-894b-b8f7199d4ce5'::uuid, 'e82fe963-b112-52e8-801d-d96a821bbe09'::uuid, 'running'::sport_key, '2026-09-05T09:30:00+02:00'::timestamptz, 70, '16beb95a-c1fd-5efc-8c1c-ebe1e84cda37'::uuid, 'Retiro', 4, 6, '8 km · 5:30–6:00 min/km', 8, 'cafe'::third_half, '4058b9d3-ae67-5e6a-80d3-41751c90ebe1'::uuid, 'todos'::audience, 'Nos vemos en la puerta, salimos puntuales.'),
  ('92f6059e-0def-504b-85f9-8376cef5d043'::uuid, 'f81f6254-c330-5816-8654-0078b030e002'::uuid, 'running'::sport_key, '2026-09-06T10:00:00+02:00'::timestamptz, 60, '4fd24052-c971-59c0-8842-e00b7d726616'::uuid, 'Arganzuela', 2, 4, '6 km · más de 6:00 min/km', 10, 'desayuno'::third_half, '123bd668-b801-56f6-8b65-356468d28d2a'::uuid, 'todos'::audience, 'Ritmo de charla. Si hace falta, paramos.'),
  ('65842273-89ad-5341-8ba2-9883a5c60d8b'::uuid, '0860daa4-3ee9-5a39-821c-4c377931613c'::uuid, 'running'::sport_key, '2026-09-08T20:00:00+02:00'::timestamptz, 60, '5a346390-1187-560d-81ba-77df35af0353'::uuid, 'Moncloa-Aravaca', 5, 8, 'Series · 5:00–5:30 min/km', 6, 'ninguno'::third_half, null::uuid, 'todos'::audience, '6x800. Traed agua.'),
  ('12e3a37f-f57b-5fab-8072-87e66e884781'::uuid, '3aac0bdc-073a-58b6-86d9-63cf91dad2f5'::uuid, 'running'::sport_key, '2026-09-10T19:30:00+02:00'::timestamptz, 55, '27b93037-03c3-5bd0-80c8-b5a2b30c785e'::uuid, 'Moncloa-Aravaca', 3, 5, '7 km suaves', 8, 'cana'::third_half, '455d1cd0-a375-5719-80c0-2b6c53a89d2f'::uuid, 'solo_mujeres'::audience, 'Grupo de chicas, primera vez bienvenida.'),
  ('e1234508-c11e-58d0-89f9-a909f3640383'::uuid, '86eabb55-dac2-5716-8817-45c60e857a92'::uuid, 'padel'::sport_key, '2026-09-04T19:00:00+02:00'::timestamptz, 90, '28692441-bf02-5052-8ca1-8c9ac1ef71da'::uuid, 'Salamanca', 5, 7, 'Nivel 3,5–4,0', 4, 'cana'::third_half, null::uuid, 'todos'::audience, 'Falta uno. Pista pagada, se divide entre cuatro.'),
  ('6dc5cce6-3eb0-5880-8a0f-c3b25f1ae21e'::uuid, '4da925aa-66d6-5e02-8046-46a8cd5e197f'::uuid, 'padel'::sport_key, '2026-09-07T11:00:00+02:00'::timestamptz, 90, '6a5f6ab2-e48c-5201-828f-74fbc644dbfb'::uuid, 'Chamberí', 3, 5, 'Nivel 2,5–3,0', 4, 'cafe'::third_half, '123bd668-b801-56f6-8b65-356468d28d2a'::uuid, 'todos'::audience, 'Partido tranquilo de domingo.'),
  ('84ce0749-264f-572d-8c46-04495ed84c77'::uuid, '86eabb55-dac2-5716-8817-45c60e857a92'::uuid, 'padel'::sport_key, '2026-09-11T20:30:00+02:00'::timestamptz, 90, '28692441-bf02-5052-8ca1-8c9ac1ef71da'::uuid, 'Salamanca', 5, 7, 'Nivel 3,5–4,0', 4, 'cana'::third_half, null::uuid, 'todos'::audience, 'Viernes, y luego caña obligatoria.'),
  ('57d00e7f-9035-5b4e-8520-a4c86f740063'::uuid, '91cbe3c1-9c48-5eeb-8007-5c731ae2c526'::uuid, 'futbol'::sport_key, '2026-09-06T18:00:00+02:00'::timestamptz, 90, '4f5ab9a0-70ca-55d3-84f3-45be1683fcf7'::uuid, 'Centro', 3, 7, 'Fútbol 7 · recreativo', 14, 'cana'::third_half, '455d1cd0-a375-5719-80c0-2b6c53a89d2f'::uuid, 'todos'::audience, 'Traigo petos y balón. 5 € cada uno por el campo.'),
  ('9c3470ae-7f61-5f8c-8dbd-4f2fcf463595'::uuid, '91cbe3c1-9c48-5eeb-8007-5c731ae2c526'::uuid, 'futbol'::sport_key, '2026-09-13T18:00:00+02:00'::timestamptz, 90, '4f5ab9a0-70ca-55d3-84f3-45be1683fcf7'::uuid, 'Centro', 3, 7, 'Fútbol 7 · recreativo', 14, 'cana'::third_half, '455d1cd0-a375-5719-80c0-2b6c53a89d2f'::uuid, 'todos'::audience, 'La de todos los domingos.'),
  ('222e933d-3862-5489-8c56-f2463928a1bf'::uuid, '0860daa4-3ee9-5a39-821c-4c377931613c'::uuid, 'escalada'::sport_key, '2026-09-09T19:00:00+02:00'::timestamptz, 120, '3f41657c-6aa8-5698-829b-67e9eb3dfc78'::uuid, 'Chamberí', 3, 7, 'Boulder · 5 a 6c', 6, 'cana'::third_half, null::uuid, 'todos'::audience, 'Si no has escalado nunca, mejor. Te enseñamos.'),
  ('1c3c2307-a191-5d9a-8e08-a15671dd6173'::uuid, 'e82fe963-b112-52e8-801d-d96a821bbe09'::uuid, 'escalada'::sport_key, '2026-09-16T19:00:00+02:00'::timestamptz, 120, '3f41657c-6aa8-5698-829b-67e9eb3dfc78'::uuid, 'Chamberí', 2, 5, 'Boulder · iniciación', 6, 'cafe'::third_half, '123bd668-b801-56f6-8b65-356468d28d2a'::uuid, 'todos'::audience, 'Alquiler de pies de gato en el propio rocódromo.'),
  ('d3bd436a-4212-538f-897c-b72108749ebc'::uuid, 'ddfcc222-85b7-52c1-8e5f-a97049c85617'::uuid, 'ciclismo'::sport_key, '2026-09-12T08:00:00+02:00'::timestamptz, 210, 'c865aab3-0e14-5a54-8a81-67e4082bc9a9'::uuid, 'Moncloa-Aravaca', 6, 8, '70 km · 26–30 km/h · carretera', 8, 'desayuno'::third_half, null::uuid, 'todos'::audience, 'Salida puntual, nadie se queda solo.'),
  ('92bf566f-9ed9-55a4-8efe-bae6417cd6e8'::uuid, 'd799f45e-241d-5a1f-81b5-a4c06b9f81d1'::uuid, 'hyrox'::sport_key, '2026-09-05T07:30:00+02:00'::timestamptz, 60, 'abde3ccc-5bc7-5ebd-842b-394b556d39e4'::uuid, 'Moncloa-Aravaca', 5, 8, 'Intermedio', 10, 'cafe'::third_half, null::uuid, 'todos'::audience, 'Antes de trabajar. Sí, a las 7:30.'),
  ('5584ab55-8b88-5ec0-8c53-46aad402aa65'::uuid, 'b1b0b994-6363-5ecf-81b4-7751f9954aa3'::uuid, 'baloncesto'::sport_key, '2026-09-07T19:00:00+02:00'::timestamptz, 90, 'c2f7189f-75c9-5366-88d1-2127006b5545'::uuid, 'Chamartín', 3, 6, '3x3 · recreativo', 10, 'cana'::third_half, null::uuid, 'todos'::audience, 'Pistas de arriba. Si llueve, se cancela.'),
  ('c938103f-ee65-57a2-8c6e-e3e1abdbb46b'::uuid, '3aac0bdc-073a-58b6-86d9-63cf91dad2f5'::uuid, 'senderismo'::sport_key, '2026-09-13T08:30:00+02:00'::timestamptz, 360, 'abfc2ad1-57c7-5339-81eb-1b0ec03b4cf0'::uuid, 'Barajas', 3, 6, 'Sierra · 14 km · desnivel medio', 12, 'comida'::third_half, null::uuid, 'todos'::audience, 'Punto de encuentro para compartir coche. Salimos a la Sierra.')
) as v (id, host_id, sport, starts_at, duration_min, venue_id, distrito,
         level_min, level_max, level_display, capacity, third_half, third_half_venue_id,
         audience, meeting_note)
on conflict (id) do update set
  starts_at = excluded.starts_at, capacity = excluded.capacity,
  level_display = excluded.level_display, meeting_note = excluded.meeting_note;

drop function seed_shift_days();
