/**
 * seed-madrid.json → supabase/seed.sql
 *
 *   pnpm db:seed:gen
 *
 * Two things this does that a hand-written seed wouldn't:
 *
 * 1. Plan dates are emitted as an offset, not as fixed timestamps. The JSON's
 *    plans sit in a fixed September week; a seed that hardcodes them produces
 *    an empty deck the moment that week passes, and `plans.future_start` then
 *    rejects the insert outright. Instead every plan is shifted forward by a
 *    whole number of weeks, computed at apply time, so weekdays and times of
 *    day survive (the Sunday pachanga stays on Sunday) and the deck is always
 *    populated with upcoming plans.
 * 2. IDs are derived deterministically from the JSON keys, so re-running the
 *    seed updates rows instead of duplicating them.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const seed = JSON.parse(readFileSync(join(ROOT, 'supabase/seed-madrid.json'), 'utf8'));

/** Stable UUIDv5-shaped id from a namespace and a key. */
function uuid(ns: string, key: string): string {
  const h = createHash('sha1').update(`dorsal:${ns}:${key}`).digest('hex');
  return [h.slice(0, 8), h.slice(8, 12), `5${h.slice(13, 16)}`, `8${h.slice(17, 20)}`, h.slice(20, 32)].join('-');
}
const q = (v: unknown): string =>
  v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const num = (v: unknown): string => (v === null || v === undefined ? 'null' : String(v));

type Venue = { id: string; name: string; kind: string; distrito: string; lat: number; lng: number; verified: boolean };
type Profile = {
  id: string; display_name: string; dorsal_number: number; birth_year: number;
  gender: string; distrito: string; travel_km: number; bio: string;
  sports: { sport: string; level_norm: number }[];
};
type Plan = {
  host: string; sport: string; starts_at: string; duration_min: number; venue: string;
  distrito: string; level_min: number; level_max: number; level_display: string;
  capacity: number; third_half: string; third_half_venue: string | null;
  audience: string; meeting_note: string;
};

const venues = seed.venues as Venue[];
const profiles = seed.demo_profiles as Profile[];
const plans = seed.demo_plans as Plan[];

// The whole-week shift is anchored on the earliest seeded plan.
const anchor = plans
  .map((p) => new Date(p.starts_at).getTime())
  .reduce((a, b) => Math.min(a, b));
const anchorIso = new Date(anchor).toISOString();

const out: string[] = [];
out.push(`-- GENERATED by scripts/generate-seed.ts from seed-madrid.json. Do not edit.
--
-- Demo profiles, venues and plans exist so the deck is never empty in
-- development. Every row carries is_seed = true:
--
--   delete from plans where is_seed; delete from profiles where is_seed;
--
-- 01-PRD §Cold start: a deck that is mostly seed data with nobody joining is
-- worse than a small honest deck. Delete these as real supply arrives.

-- Whole weeks to add to every seeded plan so the deck always sits in the
-- future. Written inline rather than as a temporary table so the file applies
-- identically through psql, the Supabase CLI and the management API, none of
-- which agree about session state.
create or replace function seed_shift_days() returns int
language sql stable as $fn$
  select greatest(
           0,
           ceil(extract(epoch from (now() + interval '12 hours' - timestamptz ${q(anchorIso)}))
                / 604800.0)
         )::int * 7;
$fn$;
`);

out.push(`\n-- ── venues ──────────────────────────────────────────────────────────────────`);
out.push(`insert into venues (id, slug, name, kind, distrito, lat, lng, verified, is_seed) values`);
out.push(
  venues
    .map(
      (v) =>
        `  (${q(uuid('venue', v.id))}, ${q(v.id)}, ${q(v.name)}, ${q(v.kind)}, ${q(v.distrito)}, ` +
        `${num(v.lat)}, ${num(v.lng)}, ${v.verified ? 'true' : 'false'}, true)`,
    )
    .join(',\n') + `\non conflict (id) do update set
  name = excluded.name, kind = excluded.kind, distrito = excluded.distrito,
  lat = excluded.lat, lng = excluded.lng, verified = excluded.verified;`,
);

out.push(`\n-- ── demo accounts ───────────────────────────────────────────────────────────
-- Shadow auth rows with no password: they cannot sign in, they only exist so
-- the profiles foreign key holds.`);
out.push(`insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, created_at, updated_at) values`);
out.push(
  profiles
    .map(
      (p) =>
        `  ('00000000-0000-0000-0000-000000000000', ${q(uuid('user', p.id))}, 'authenticated', 'authenticated', ` +
        `${q(`seed.${p.id}@dorsal.invalid`)}, now(), now(), now())`,
    )
    .join(',\n') + `\non conflict (id) do nothing;`,
);

out.push(`\ninsert into profiles (id, dorsal_number, display_name, birth_year, gender, distrito, travel_km, bio, is_seed) values`);
out.push(
  profiles
    .map(
      (p) =>
        `  (${q(uuid('user', p.id))}, ${num(p.dorsal_number)}, ${q(p.display_name)}, ${num(p.birth_year)}, ` +
        `${q(p.gender)}::gender_decl, ${q(p.distrito)}, ${num(p.travel_km)}, ${q(p.bio)}, true)`,
    )
    .join(',\n') + `\non conflict (id) do update set
  display_name = excluded.display_name, distrito = excluded.distrito,
  travel_km = excluded.travel_km, bio = excluded.bio;`,
);

out.push(`\ninsert into user_sports (user_id, sport, level_norm) values`);
out.push(
  profiles
    .flatMap((p) =>
      p.sports.map(
        (s) => `  (${q(uuid('user', p.id))}, ${q(s.sport)}::sport_key, ${num(s.level_norm)})`,
      ),
    )
    .join(',\n') + `\non conflict (user_id, sport) do update set level_norm = excluded.level_norm;`,
);

out.push(`\n-- ── plans ───────────────────────────────────────────────────────────────────`);
out.push(`insert into plans (
  id, host_id, sport, starts_at, duration_min, venue_id, distrito,
  level_min, level_max, level_display, capacity, third_half, third_half_venue_id,
  audience, meeting_note, is_seed
)
select v.id, v.host_id, v.sport, v.starts_at + make_interval(days => seed_shift_days()),
       v.duration_min, v.venue_id, v.distrito, v.level_min, v.level_max, v.level_display,
       v.capacity, v.third_half, v.third_half_venue_id, v.audience, v.meeting_note, true
from (values`);
out.push(
  plans
    .map((p, i) => {
      const id = uuid('plan', `${p.host}:${p.sport}:${p.starts_at}`);
      const thirdVenue = p.third_half_venue ? q(uuid('venue', p.third_half_venue)) : 'null';
      return (
        `  (${q(id)}::uuid, ${q(uuid('user', p.host))}::uuid, ${q(p.sport)}::sport_key, ` +
        `${q(p.starts_at)}::timestamptz, ${num(p.duration_min)}, ${q(uuid('venue', p.venue))}::uuid, ` +
        `${q(p.distrito)}, ${num(p.level_min)}, ${num(p.level_max)}, ${q(p.level_display)}, ` +
        `${num(p.capacity)}, ${q(p.third_half)}::third_half, ${thirdVenue}::uuid, ` +
        `${q(p.audience)}::audience, ${q(p.meeting_note)})` +
        (i === plans.length - 1 ? '' : ',')
      );
    })
    .join('\n'),
);
out.push(`) as v (id, host_id, sport, starts_at, duration_min, venue_id, distrito,
         level_min, level_max, level_display, capacity, third_half, third_half_venue_id,
         audience, meeting_note)
on conflict (id) do update set
  starts_at = excluded.starts_at, capacity = excluded.capacity,
  level_display = excluded.level_display, meeting_note = excluded.meeting_note;`);

out.push(`\ndrop function seed_shift_days();`);

const sql = out.join('\n') + '\n';
writeFileSync(join(ROOT, 'supabase/seed.sql'), sql);
console.log(
  `supabase/seed.sql — ${venues.length} venues, ${profiles.length} profiles, ${plans.length} plans`,
);
